services:
  custom-widgets:
    build: .
    container_name: homarr-custom-widgets
    restart: unless-stopped
    environment:
      PORT: 8080
      FRAME_ANCESTORS: ""
      GEOIP_PROVIDER: "ipapi"
      DASHDOT_URL: "http://dashdot:3001"
    expose:
      - "8080"
    networks:
      - services

networks:
  services:
    external: true
