services:
  homarr-iframes:
    build: .
    container_name: homarr-iframes
    restart: unless-stopped
    environment:
      PORT: 8080
      FRAME_ANCESTORS: ""
      GEOIP_PROVIDER: "ipapi"
      DASHDOT_URL: "http://dashdot:3001"
    expose:
      - "8080"
    networks:
      services:
        aliases:
          - homarr-iframes
          - custom-widgets
          - homarr-custom-widgets

networks:
  services:
    external: true
